[package]
name = "postbud-api"
description = "HTTP API for postbud"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
postbud-core.workspace = true
postbud-db.workspace = true

anyhow.workspace = true
axum.workspace = true
base64.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower-http.workspace = true
uuid.workspace = true
